language: php

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm
    allow_failures:
        - php: 7.0

before_script:
  - composer install --dev

script:
  - php bin/phpspec run -f pretty
